# List of patient IDs
# pilot1: '101' '103' '106' '107' '110' '111' '112' '113' '114' '115' '116' '201' '204' '205'
# CLEAR: 'p01' ... 'p18'
# Enable or disable debug mode
debug_mode: false

## ========================= Dataset ===============================
patient:
  - 'p01'
  - 'p02'
  - 'p03'
  - 'p04'
  - 'p05'
  - 'p06'
  - 'p07'
  - 'p08'
  - 'p13'


dataset: "clear" # Dataset name to use : "pilot01" "clear"
dataset_task: "flicker" # "flicker" or "m_sequence"
single_event_target: "ColorLev"# "target_9_8"

# Preprocessing
preprocessing_configs: {} #{'low_pass_filter': {'cutoff': 45, 'order': 5}}
load_preprocessed_data: false # Load preprocessed data from a file
save_preprocessed_data: false # Save preprocessed data to a file

# Feature extraction
save_features: true
load_features: true
feature_extraction_configs : {
        'time_n200': {'start_time': 150, 'end_time': 250},
        'time_p300': {'start_time': 250, 'end_time': 550},
        'time_post_p300': {'start_time': 550, 'end_time': 750},
        'frequency1': {'time_start': 0, 'end_time': 500},
        'frequency2': {'time_start': 250, 'end_time': 700}
    }
feature_transformation : "normalize"  # Options: normalize, standardize, None

# Feature selection
features_selection_method : "corr"  # Options: all, corr, pre_selected
num_important_features: 100
correlation_mode: "single" # correlation based on single event or multi event Options: 'multi' or 'single'


# =========================== Training ===================================
cross_validation_mode: 'k-fold'  # Options: 'single', 'order', 'k-fold'
num_folds: 5
test_size: 0.2
load_pretrained_model: true # Load a pretrained model

# ============================= Model ====================================

method_list:
  - "xgboost"
  #- "ldgd"
  - "fast_ldgd"

metric_list:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"

# Fast LDGD Configs
fast_ldgd_configs : {'latent_dim': 2,
                    'num_inducing_points': 2,
                    'cls_weight': 1.0,
                    'reg_weight': 1.0,
                    'use_gpytorch': True,
                    'use_shared_kernel': False,
                    'shared_inducing_points': True,
                    'early_stop': None,
                    'encoder': [300, 100]}
# LDGD Configs
ldgd_configs : {'latent_dim': 1,
                    'num_inducing_points': 2,
                    'cls_weight': 1.0,
                    'reg_weight': 1.0,
                    'use_gpytorch': True,
                    'use_shared_kernel': False,
                    'shared_inducing_points': True,
                    'early_stop': None}
# XGBoost Configs
xgboost_configs : {'balance_method': 'weighting'
}

# Training LDGD
load_trained_model : False
batch_size : 100
num_epochs_train : 1000
num_epochs_test : 4000

