# List of patient IDs
patient:
  - '101'
#  - '103'
  - '106'
  - '107'
#  - '110'
#  - '111'
#  - '112'
#  - '113'
#  - '114'
#  - '115'
#  - '116'
#  - '201'
#  - '204'
#  - '205'
# Patients for CLear dataset:
#  - 'p01'
#  - 'p02'
#  - 'p03'
#  - 'p04'
#  - 'p05'
#  - 'p06'
#  - 'p07'
#  - 'p08'
#  - 'p13'

# Dataset name to use : "pilot01" "clear"
dataset: "pilot01"

# Enable or disable debug mode
debug_mode: false


method_list:
#  - "xgboost"
#  - "fast_ldgd"
  - "ldgd"

metric_list:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"

#  data
features_selection_method : "corr"  # Options: all, corr, pre_selected
feature_transformation : "normalize"  # Options: normalize, standardize, None
# for clear dtaset: ColorLev
# for pilot01 dataset (preprocessed h5 files): TargetValue
# for pilot01 dataset (raw xdf files): decision, old_new, is_go, is_correct, is_experienced
target_column : "TargetValue"
# Number of folds for cross-validation mode (It can be a number of block for pilot1 task)
cross_validation_mode: 'order'  # Options: 'order', 'kfold'
# Proportion of the dataset to include in the test split
test_size: 0.2


# LDGD Configs
data_dim : None
latent_dim : 3
num_inducing_points : 10
cls_weight : 1
use_gpytorch : True
shared_inducing_points : True

# Training LDGD
load_trained_model : False
batch_size : 100
num_epochs_train : 5000
num_epochs_test : 5000


# Save features to a file
save_features: false
# Load features from a file
load_features: false
load_pretrained_model: true # Load a pretrained model


# Dataset configs
load_epoched_data: true  # Load epoched data
save_epoched_data: false # Save epoched data to a file
load_preprocessed_data: false # Load preprocessed data from a file
save_preprocessed_data: false # Save preprocessed data to a file

